services:
  coreai-mcu-frontend:
    build:
      context: .
      target: production
    image: coreai-mcu-frontend
    container_name: coreai-mcu-frontend
    environment:
      APPINSIGHTS_CLOUDROLE: coreai-mcu-frontend-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      KNOWLEDGE_INGESTION_TOPIC: ${KNOWLEDGE_INGESTION_TOPIC:-coreai-mcu-knowledge-ingestion}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generation-request}
      EVENTS_SUBSCRIPTION: ${EVENTS_SUBSCRIPTION_TOPIC:-coreai-mcu-frontend}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-coreai-mcu-events}
      DOCUMENTS_API_BASE_URL: ${DOCUMENTS_API_BASE_URL:-coreai-mcu-documents}
      KNOWLEDGE_API_BASE_URL: ${KNOWLEDGE_API_BASE_URL:-coreai-mcu-documents}
      RESPONSES_API_BASE_URL: ${RESPONSES_API_BASE_URL:-coreai-mcu-responses}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-examplekey-644a2a30-7487-4e98-a908-b5ecd82d5225-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_CORRESPONDENCE: ${NOTIFY_TEMPLATE_CORRESPONDENCE:-37b554a1-eb2d-4f34-8170-927ec5fc3dd6}
      CARBON_COPY_EMAIL_ADDRESS: ${CARBON_COPY_EMAIL_ADDRESS}
