# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  coreai-mcu-frontend:
    build:
      target: development
    image: coreai-mcu-frontend-development
    container_name: coreai-mcu-frontend-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generation-request}${MESSAGE_QUEUE_SUFFIX}
      KNOWLEDGE_INGESTION_TOPIC: ${KNOWLEDGE_INGESTION_TOPIC:-coreai-mcu-knowledge-ingestion}${MESSAGE_QUEUE_SUFFIX}
      DOCUMENTS_API_BASE_URL: ${DOCUMENTS_API_BASE_URL:-coreai-mcu-documents}
