- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: AZUREID_CLIENT_ID
  value: "{{servicename}}-AZUREID-CLIENT-ID"
  type: "keyvault"
- key: AZUREID_CLIENT_SECRET
  value: "{{servicename}}-AZUREID-CLIENT-SECRET"
  type: "keyvault"
- key: MESSAGE_QUEUE_HOST
  value: "{{servicename}}-MESSAGE-QUEUE-HOST"
  type: "keyvault"
- key: COOKIE_PASSWORD
  value: "{{servicename}}-COOKIE-PASSWORD"
  type: "keyvault"
- key: KNOWLEDGE_INGESTION_TOPIC
  value: "crai-mcu-knowledge-ingest"
- key: GENERATION_REQUEST_TOPIC
  value: "crai-mcu-generate"
- key: TRIAGE_REQUEST_TOPIC
  value: "crai-mcu-triage"
- key: EVENTS_SUBSCRIPTION
  value: "crai-mcu-frontend"
- key: EVENTS_TOPIC_ADDRESS
  value: "crai-mcu-events"
- key: DOCUMENTS_API_BASE_URL
  value: "http://coreai-mcu-documents.crai-mcu.svc.cluster.local"
- key: KNOWLEDGE_API_BASE_URL
  value: "http://coreai-mcu-knowledge-pgv.crai-mcu.svc.cluster.local"
- key: RESPONSES_API_BASE_URL
  value: "http://coreai-mcu-responses.crai-mcu.svc.cluster.local"
- key: PROMPTS_API_BASE_URL
  value: "http://coreai-mcu-prompts.crai-mcu.svc.cluster.local"
- key: PERSONAS_API_BASE_URL
  value: "http://coreai-mcu-personas.crai-mcu.svc.cluster.local"
- key: NOTIFY_API_KEY
  value: "{{servicename}}-NOTIFY-API-KEY"
  type: "keyvault"
- key: NOTIFY_TEMPLATE_ID_CORRESPONDENCE
  value: "37b554a1-eb2d-4f34-8170-927ec5fc3dd6"
- key: AUTHENTICATION_ENABLED
  value: "{{servicename}}-AUTHENTICATION-ENABLED"
  type: "keyvault"
